"use client";

import React, { useState, useRef } from "react";
import { Upload, FileText, X, Lock, Download, Eye, EyeOff, Wand2, Copy, Check, Sparkles, ShieldCheck } from "lucide-react";
import { UploadCard } from "@/components/tools/upload-card";
import { loadPdfjs } from "@/lib/pdf-libs";

export default function ProtectPdfPage() {
    const [file, setFile] = useState<{ name: string; size: string; rawFile: File } | null>(null);
    const [isDragging, setIsDragging] = useState(false);
    const [password, setPassword] = useState("");
    const [confirmPassword, setConfirmPassword] = useState("");
    const [showPassword, setShowPassword] = useState(false);
    const [processing, setProcessing] = useState(false);
    const [done, setDone] = useState(false);
    const [copied, setCopied] = useState(false);
    const [autoGenerated, setAutoGenerated] = useState(false);
    const [numPages, setNumPages] = useState<number>(0);
    const [error, setError] = useState("");
    
    const inputRef = useRef<HTMLInputElement>(null);
    const canvasRefs = useRef<HTMLCanvasElement[]>([]);

    const formatSize = (bytes: number) => {
        if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(0)} KB`;
        return `${(bytes / (1024 * 1024)).toFixed(1)} MB`;
    };

    const handleFile = async (fileList: FileList | null) => {
        if (!fileList || fileList.length === 0) return;
        const f = fileList[0];
        if (f.type !== "application/pdf") return;
        
        setFile({ name: f.name, size: formatSize(f.size), rawFile: f });
        setDone(false);
        setError("");

        try {
            const arrayBuffer = await f.arrayBuffer();
            const pdfjsLib = await loadPdfjs();
            const loadingTask = pdfjsLib.getDocument({ data: arrayBuffer });
            const pdfDoc = await loadingTask.promise;
            setNumPages(pdfDoc.numPages);

            setTimeout(async () => {
                for (let i = 1; i <= pdfDoc.numPages; i++) {
                    const page = await pdfDoc.getPage(i);
                    const viewport = page.getViewport({ scale: 1.0 });
                    const canvas = canvasRefs.current[i - 1];
                    if (canvas) {
                        const context = canvas.getContext("2d");
                        canvas.height = viewport.height;
                        canvas.width = viewport.width;
                        if (context) {
                            await page.render({ canvasContext: context, viewport }).promise;
                        }
                    }
                }
            }, 100);
        } catch (err) {
            setError("Failed to load PDF preview.");
        }
    };

    const passwordsMatch = password.length > 0 && password === confirmPassword;

    const generatePassword = () => {
        const chars = "ABCDEFGHJKMNPQRSTUVWXYZabcdefghijkmnpqrstuvwxyz23456789!@#$%&*";
        let result = "";
        for (let i = 0; i < 14; i++) {
            result += chars[Math.floor(Math.random() * chars.length)];
        }
        setPassword(result);
        setConfirmPassword(result);
        setShowPassword(true);
        setAutoGenerated(true);
        setCopied(false);
    };

    const handleCopy = () => {
        if (!password) return;
        navigator.clipboard.writeText(password);
        setCopied(true);
        setTimeout(() => setCopied(false), 1500);
    };

    const handleProtect = async (e: React.FormEvent) => {
        e.preventDefault();
        if (!file) {
            setError("Please select a PDF file.");
            return;
        }
        if (!password) {
            setError("Please enter a password.");
            return;
        }
        if (!passwordsMatch) {
            setError("Passwords do not match.");
            return;
        }

        setProcessing(true);
        setError("");

        const formData = new FormData();
        formData.append("file", file.rawFile);
        formData.append("password", password);

        try {
            const res = await fetch("/api/protect-pdf", {
                method: "POST",
                body: formData,
            });

            if (!res.ok) {
                const data = await res.json();
                throw new Error(data.error || "Failed to protect PDF");
            }

            const blob = await res.blob();
            const url = window.URL.createObjectURL(blob);
            const a = document.createElement("a");
            a.href = url;
            a.download = `${file.name.replace(/\.[^/.]+$/, "")}-protected.pdf`;
            document.body.appendChild(a);
            a.click();
            a.remove();
            window.URL.revokeObjectURL(url);
            setDone(true);
        } catch (err: any) {
            setError(err.message || "An unexpected error occurred.");
        } finally {
            setProcessing(false);
        }
    };

    return (
        <div className="min-h-screen bg-background text-fg flex flex-col items-center justify-center p-6 transition-colors">
            {!file ? (
                <div className="max-w-xl w-full bg-card border border-card rounded-3xl p-8 shadow-2xl space-y-6">
                    <div className="text-center space-y-3">
                        <div className="inline-flex items-center space-x-1.5 text-xs font-semibold uppercase tracking-wider text-purple-900 dark:text-cyan-400 bg-purple-50 dark:bg-cyan-950/60 px-3 py-1.5 rounded-full border border-purple-200 dark:border-cyan-800/40">
                            <Sparkles size={13} />
                            <span>Document Conversion Suite</span>
                        </div>
                        <h1 className="text-3xl font-bold tracking-tight text-fg">Protect PDF</h1>
                        <p className="text-muted text-sm">
                            Add a password so only people you choose can open this file.
                        </p>
                    </div>

                    <UploadCard
                        onFiles={handleFile}
                        title="Click to upload PDF document"
                        hint="Supports text documents and reports"
                        note={
                            <>
                                <ShieldCheck size={14} className="text-[var(--primary)]" />
                                <span>Secure PDF text extraction • No file retention</span>
                            </>
                        }
                    />
                </div>
            ) : (
                <div className="max-w-xl w-full bg-card border border-card rounded-3xl p-8 shadow-2xl space-y-6">
                    <div className="text-center space-y-3">
                        <div className="inline-flex items-center space-x-1.5 text-xs font-semibold uppercase tracking-wider text-purple-900 dark:text-cyan-400 bg-purple-50 dark:bg-cyan-950/60 px-3 py-1.5 rounded-full border border-purple-200 dark:border-cyan-800/40">
                            <Sparkles size={13} />
                            <span>Document Conversion Suite</span>
                        </div>
                        <h1 className="text-3xl font-bold tracking-tight text-fg">Protect PDF</h1>
                        <p className="text-muted text-sm">
                            Configure encryption settings for your document.
                        </p>
                    </div>

                    <form onSubmit={handleProtect} className="space-y-6">
                        <div className="flex items-center gap-3 p-3 rounded-xl bg-card border border-card">
                            <div className="w-9 h-9 rounded-lg bg-purple-100 dark:bg-cyan-500/10 text-purple-900 dark:text-cyan-400 flex items-center justify-center shrink-0 border border-purple-200 dark:border-cyan-500/20">
                                <FileText size={16} />
                            </div>
                            <div className="flex-1 min-w-0">
                                <p className="text-fg text-sm truncate font-medium">{file.name}</p>
                                <p className="text-muted text-xs">{file.size}</p>
                            </div>
                            <button type="button" onClick={() => { setFile(null); setDone(false); setNumPages(0); }} className="text-slate-400 hover:text-purple-900 dark:hover:text-cyan-400 shrink-0">
                                <X size={16} />
                            </button>
                        </div>

                        {numPages > 0 && (
                            <div className="space-y-2 bg-card p-4 rounded-xl border border-card">
                                <span className="text-xs font-semibold uppercase tracking-wider text-muted">
                                    Document Preview ({numPages} Pages)
                                </span>
                                <div className="space-y-4 max-h-56 overflow-y-auto flex flex-col items-center p-2 rounded-lg bg-slate-200/50 dark:bg-black/40 border border-card">
                                    {Array.from({ length: numPages }, (_, i) => (
                                        <div key={i} className="shadow-lg bg-white p-1.5 rounded">
                                            <p className="text-[10px] text-gray-500 mb-1 text-center font-medium">Page {i + 1}</p>
                                            <canvas
                                                ref={(el) => {
                                                    if (el) canvasRefs.current[i] = el;
                                                }}
                                                className="max-h-48 object-contain rounded"
                                            />
                                        </div>
                                    ))}
                                </div>
                            </div>
                        )}

                        <div className="space-y-4">
                            <div>
                                <div className="flex items-center justify-between mb-2">
                                    <label className="text-xs font-semibold uppercase tracking-wider text-muted">
                                        Password
                                    </label>
                                    <button
                                        type="button"
                                        onClick={generatePassword}
                                        className="inline-flex items-center gap-1 text-xs font-medium text-purple-900 dark:text-cyan-400 hover:underline"
                                    >
                                        <Wand2 size={13} />
                                        Generate strong password
                                    </button>
                                </div>
                                <div className="relative">
                                    <input
                                        type={showPassword ? "text" : "password"}
                                        value={password}
                                        onChange={(e) => { setPassword(e.target.value); setAutoGenerated(false); setCopied(false); }}
                                        placeholder="Enter password"
                                        className="w-full bg-card border border-card rounded-xl px-4 py-3 pr-20 text-fg focus:outline-none focus:border-purple-900 dark:focus:border-cyan-500 text-sm"
                                    />
                                    <div className="absolute right-3 top-1/2 -translate-y-1/2 flex items-center gap-2">
                                        {autoGenerated && password.length > 0 && (
                                            <button type="button" onClick={handleCopy} className="text-slate-400 hover:text-purple-900 dark:hover:text-cyan-400" title="Copy password">
                                                {copied ? <Check size={16} className="text-emerald-600 dark:text-emerald-400" /> : <Copy size={16} />}
                                            </button>
                                        )}
                                        <button type="button" onClick={() => setShowPassword(!showPassword)} className="text-slate-400 hover:text-purple-900 dark:hover:text-cyan-400">
                                            {showPassword ? <EyeOff size={16} /> : <Eye size={16} />}
                                        </button>
                                    </div>
                                </div>
                                {autoGenerated && (
                                    <p className="text-xs text-muted mt-1">
                                        We generated this password for you — make sure to copy and save it before continuing.
                                    </p>
                                )}
                            </div>

                            <div>
                                <label className="block text-xs font-semibold uppercase tracking-wider text-muted mb-2">
                                    Confirm Password
                                </label>
                                <input
                                    type={showPassword ? "text" : "password"}
                                    value={confirmPassword}
                                    onChange={(e) => { setConfirmPassword(e.target.value); setAutoGenerated(false); }}
                                    placeholder="Re-enter password"
                                    className="w-full bg-card border border-card rounded-xl px-4 py-3 text-fg focus:outline-none focus:border-purple-900 dark:focus:border-cyan-500 text-sm"
                                />
                                {confirmPassword.length > 0 && !passwordsMatch && (
                                    <p className="text-xs text-red-600 dark:text-cyan-400 mt-1">Passwords do not match</p>
                                )}
                            </div>
                        </div>

                        {error && (
                            <div className="bg-red-50 dark:bg-red-950/50 border border-red-200 dark:border-red-800/80 text-red-700 dark:text-red-300 text-xs px-4 py-3 rounded-xl">
                                {error}
                            </div>
                        )}

                        <button
                            type="submit"
                            disabled={processing || !passwordsMatch || !file}
                            className="w-full bg-slate-900 dark:bg-[var(--card)] border border-slate-900 dark:border-slate-700/80 hover:bg-slate-800 dark:hover:bg-[var(--card)] text-white font-semibold py-3.5 px-4 rounded-xl transition-all shadow-lg disabled:opacity-50 text-sm tracking-wide flex items-center justify-center gap-2"
                        >
                            {processing ? (
                                "Protecting PDF..."
                            ) : done ? (
                                <>
                                    <Download size={18} />
                                    Download Protected PDF Again
                                </>
                            ) : (
                                "Protect and Download PDF"
                            )}
                        </button>
                    </form>

                    <div className="flex items-center justify-center space-x-2 text-xs text-muted pt-2 border-t border-card">
                        <ShieldCheck size={16} className="text-purple-900 dark:text-cyan-400" />
                        <span>Secure client-side processing • Password encrypted securely</span>
                    </div>
                </div>
            )}
        </div>
    );
}