"use client";

<<<<<<< HEAD
import { useState, useRef } from "react";
import { Upload, FileText, X, Lock, Download, Eye, EyeOff, Wand2, Copy, Check } from "lucide-react";

export default function ProtectPdfPage() {
    const [file, setFile] = useState<{ name: string; size: string } | null>(null);
    const [isDragging, setIsDragging] = useState(false);
    const [password, setPassword] = useState("");
    const [confirmPassword, setConfirmPassword] = useState("");
    const [showPassword, setShowPassword] = useState(false);
    const [processing, setProcessing] = useState(false);
    const [done, setDone] = useState(false);
    const [copied, setCopied] = useState(false);
    const [autoGenerated, setAutoGenerated] = useState(false);
    const inputRef = useRef<HTMLInputElement>(null);

    const formatSize = (bytes: number) => {
        if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(0)} KB`;
        return `${(bytes / (1024 * 1024)).toFixed(1)} MB`;
    };

    const handleFile = (fileList: FileList | null) => {
        if (!fileList || fileList.length === 0) return;
        const f = fileList[0];
        if (f.type !== "application/pdf") return;
        setFile({ name: f.name, size: formatSize(f.size) });
        setDone(false);
    };

    const passwordsMatch = password.length > 0 && password === confirmPassword;

    const generatePassword = () => {
        const chars = "ABCDEFGHJKMNPQRSTUVWXYZabcdefghijkmnpqrstuvwxyz23456789!@#$%&*";
        let result = "";
        for (let i = 0; i < 14; i++) {
            result += chars[Math.floor(Math.random() * chars.length)];
        }
        setPassword(result);
        setConfirmPassword(result);
        setShowPassword(true);
        setAutoGenerated(true);
        setCopied(false);
    };

    const handleCopy = () => {
        if (!password) return;
        navigator.clipboard.writeText(password);
        setCopied(true);
        setTimeout(() => setCopied(false), 1500);
    };

    const handleProtect = () => {
        setProcessing(true);
        setTimeout(() => {
            setProcessing(false);
            setDone(true);
        }, 1800);
    };

    return (
        <div className="max-w-3xl mx-auto">
            <div className="text-center mb-10">
                <div className="w-14 h-14 mx-auto rounded-2xl bg-red-50 flex items-center justify-center mb-4">
                    <Lock className="text-[var(--primary)]" size={26} />
                </div>
                <h1 className="text-2xl font-bold text-fg">Protect PDF</h1>
                <p className="text-muted text-sm mt-1">Add a password so only people you choose can open this file.</p>
            </div>

            {!file ? (
                <div
                    onDragOver={(e) => { e.preventDefault(); setIsDragging(true); }}
                    onDragLeave={() => setIsDragging(false)}
                    onDrop={(e) => { e.preventDefault(); setIsDragging(false); handleFile(e.dataTransfer.files); }}
                    onClick={() => inputRef.current?.click()}
                    className={`cursor-pointer rounded-2xl border-2 border-dashed p-10 text-center transition-colors ${isDragging ? "border-[var(--primary)] bg-red-50" : "border-card bg-card"
                        }`}
                >
                    <input ref={inputRef} type="file" accept="application/pdf" hidden onChange={(e) => handleFile(e.target.files)} />
                    <Upload className="mx-auto text-muted mb-3" size={28} />
                    <p className="text-fg font-medium text-sm">Drag & drop a PDF file here</p>
                    <p className="text-muted text-xs mt-1">or click to browse</p>
                </div>
            ) : (
                <>
                    <div className="flex items-center gap-3 p-3 rounded-xl bg-card border border-card">
                        <div className="w-9 h-9 rounded-lg bg-red-50 flex items-center justify-center shrink-0">
                            <FileText size={16} className="text-[var(--primary)]" />
                        </div>
                        <div className="flex-1 min-w-0">
                            <p className="text-fg text-sm truncate">{file.name}</p>
                            <p className="text-muted text-xs">{file.size}</p>
                        </div>
                        <button onClick={() => { setFile(null); setDone(false); }} className="text-muted hover:text-[var(--primary)] shrink-0">
                            <X size={16} />
                        </button>
                    </div>

                    <div className="mt-6 p-5 rounded-2xl bg-card border border-card space-y-4">
                        <div className="flex items-center justify-between">
                            <label className="text-xs text-muted block mb-1">Set password</label>
                            <button
                                type="button"
                                onClick={generatePassword}
                                className="inline-flex items-center gap-1 text-xs font-medium text-[var(--primary)] hover:opacity-80 mb-1"
                            >
                                <Wand2 size={13} />
                                Generate strong password
                            </button>
                        </div>
                        <div className="relative">
                            <input
                                type={showPassword ? "text" : "password"}
                                value={password}
                                onChange={(e) => { setPassword(e.target.value); setAutoGenerated(false); setCopied(false); }}
                                placeholder="Enter a password"
                                className="w-full px-3 py-2 pr-20 rounded-lg border border-card text-fg text-sm bg-card focus:outline-none focus:border-[var(--primary)]"
                            />
                            <div className="absolute right-3 top-1/2 -translate-y-1/2 flex items-center gap-2">
                                {autoGenerated && password.length > 0 && (
                                    <button type="button" onClick={handleCopy} className="text-muted hover:text-[var(--primary)]" title="Copy password">
                                        {copied ? <Check size={16} className="text-green-600" /> : <Copy size={16} />}
                                    </button>
                                )}
                                <button type="button" onClick={() => setShowPassword(!showPassword)} className="text-muted hover:text-[var(--primary)]">
                                    {showPassword ? <EyeOff size={16} /> : <Eye size={16} />}
                                </button>
                            </div>
                        </div>
                        {autoGenerated && (
                            <p className="text-xs text-muted -mt-2">
                                We generated this password for you — make sure to copy and save it before continuing.
                            </p>
                        )}

                        <div>
                            <label className="text-xs text-muted block mb-1">Confirm password</label>
                            <input
                                type={showPassword ? "text" : "password"}
                                value={confirmPassword}
                                onChange={(e) => { setConfirmPassword(e.target.value); setAutoGenerated(false); }}
                                placeholder="Re-enter the password"
                                className="w-full px-3 py-2 rounded-lg border border-card text-fg text-sm bg-card focus:outline-none focus:border-[var(--primary)]"
                            />
                            {confirmPassword.length > 0 && !passwordsMatch && (
                                <p className="text-xs text-[var(--primary)] mt-1">Passwords don't match</p>
                            )}
                        </div>
                    </div>

                    <div className="mt-8 text-center">
                        {!done ? (
                            <button
                                onClick={handleProtect}
                                disabled={processing || !passwordsMatch}
                                className="px-8 py-3 rounded-full bg-[var(--primary)] text-white font-medium hover:bg-[var(--primary-hover)] transition-colors disabled:opacity-60"
                            >
                                {processing ? "Protecting..." : "Protect PDF"}
                            </button>
                        ) : (
                            <button className="inline-flex items-center gap-2 px-8 py-3 rounded-full bg-[var(--primary)] text-white font-medium hover:bg-[var(--primary-hover)] transition-colors">
                                <Download size={18} />
                                Download Protected PDF
                            </button>
                        )}
                    </div>
                </>
            )}
        </div>
    );
=======
import React, { useState, useRef } from "react";
import * as pdfjsLib from "pdfjs-dist";

// Set worker path for PDF.js
pdfjsLib.GlobalWorkerOptions.workerSrc = `//cdnjs.cloudflare.com/ajax/libs/pdf.js/${pdfjsLib.version}/pdf.worker.min.js`;

export default function ProtectPDFPage() {
  const [file, setFile] = useState<File | null>(null);
  const [password, setPassword] = useState("");
  const [confirmPassword, setConfirmPassword] = useState("");
  const [numPages, setNumPages] = useState<number>(0);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState("");
  const canvasRefs = useRef<HTMLCanvasElement[]>([]);

  // Handle file selection and load PDF preview
  const handleFileChange = async (e: React.ChangeEvent<HTMLInputElement>) => {
    const selectedFile = e.target.files?.[0];
    if (selectedFile && selectedFile.type === "application/pdf") {
      setFile(selectedFile);
      setError("");
      const arrayBuffer = await selectedFile.arrayBuffer();
      const loadingTask = pdfjsLib.getDocument({ data: arrayBuffer });
      const pdfDoc = await loadingTask.promise;
      setNumPages(pdfDoc.numPages);

      // Render each page
      setTimeout(async () => {
        for (let i = 1; i <= pdfDoc.numPages; i++) {
          const page = await pdfDoc.getPage(i);
          const viewport = page.getViewport({ scale: 1.0 });
          const canvas = canvasRefs.current[i - 1];
          if (canvas) {
            const context = canvas.getContext("2d");
            canvas.height = viewport.height;
            canvas.width = viewport.width;
            await page.render({ canvasContext: context!, viewport }).promise;
          }
        }
      }, 100);
    }
  };

  const handleProtect = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!file) {
      setError("Please select a PDF file.");
      return;
    }
    if (!password) {
      setError("Please enter a password.");
      return;
    }
    if (password !== confirmPassword) {
      setError("Passwords do not match.");
      return;
    }

    setLoading(true);
    setError("");

    const formData = new FormData();
    formData.append("file", file);
    formData.append("password", password);

    try {
      const res = await fetch("/api/protect-pdf", {
        method: "POST",
        body: formData,
      });

      if (!res.ok) {
        const data = await res.json();
        throw new Error(data.error || "Failed to protect PDF");
      }

      const blob = await res.blob();
      const url = window.URL.createObjectURL(blob);
      const a = document.createElement("a");
      a.href = url;
      a.download = `${file.name.replace(/\.[^/.]+$/, "")}-protected.pdf`;
      document.body.appendChild(a);
      a.click();
      a.remove();
      window.URL.revokeObjectURL(url);
    } catch (err: any) {
      setError(err.message || "An unexpected error occurred.");
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="min-h-screen bg-[#070b14] text-slate-100 flex flex-col items-center justify-center p-6">
      <div className="max-w-xl w-full bg-[#111827] border border-slate-800/80 rounded-3xl p-8 shadow-2xl space-y-6">
        
        {/* Header Badge & Title */}
        <div className="text-center space-y-3">
          <div className="inline-flex items-center space-x-1.5 text-xs font-semibold uppercase tracking-wider text-cyan-400 bg-cyan-950/60 px-3 py-1.5 rounded-full border border-cyan-800/40">
            <span>✨</span>
            <span>Professional PDF Toolkit</span>
          </div>
          <h1 className="text-3xl font-bold tracking-tight text-white">Protect PDF</h1>
          <p className="text-slate-400 text-sm">
            Encrypt your PDF document with a secure password protection.
          </p>
        </div>

        <form onSubmit={handleProtect} className="space-y-6">
          {/* Drag & Drop File Upload Box */}
          <div className="border-2 border-dashed border-cyan-500/40 hover:border-cyan-500 transition-colors rounded-2xl p-6 text-center bg-[#0d1322]/80 relative group">
            <input
              type="file"
              accept=".pdf"
              onChange={handleFileChange}
              className="absolute inset-0 w-full h-full opacity-0 cursor-pointer"
              id="pdf-upload"
            />
            <div className="flex flex-col items-center space-y-3">
              <div className="w-12 h-12 bg-cyan-500/10 text-cyan-400 rounded-2xl flex items-center justify-center border border-cyan-500/20 group-hover:scale-105 transition-transform">
                <svg className="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-8l-4-4m0 0L8 8m4-4v12" />
                </svg>
              </div>
              <div>
                <p className="text-sm font-semibold text-slate-200">
                  {file ? file.name : "Click to upload or drag & drop"}
                </p>
                <p className="text-xs text-slate-400 mt-1">PDF documents up to 50MB</p>
              </div>
            </div>
          </div>

          {/* Password Inputs */}
          <div className="space-y-4">
            <div>
              <label className="block text-xs font-semibold uppercase tracking-wider text-slate-400 mb-2">
                Password
              </label>
              <input
                type="password"
                value={password}
                onChange={(e) => setPassword(e.target.value)}
                placeholder="Enter password"
                className="w-full bg-[#0d1322] border border-slate-700/80 rounded-xl px-4 py-3 text-slate-100 focus:outline-none focus:border-cyan-500 text-sm"
              />
            </div>

            <div>
              <label className="block text-xs font-semibold uppercase tracking-wider text-slate-400 mb-2">
                Confirm Password
              </label>
              <input
                type="password"
                value={confirmPassword}
                onChange={(e) => setConfirmPassword(e.target.value)}
                placeholder="Re-enter password"
                className="w-full bg-[#0d1322] border border-slate-700/80 rounded-xl px-4 py-3 text-slate-100 focus:outline-none focus:border-cyan-500 text-sm"
              />
            </div>
          </div>

          {/* All Pages Preview Section */}
          {numPages > 0 && (
            <div className="space-y-2 bg-[#0d1322] p-4 rounded-xl border border-slate-700/80">
              <span className="text-xs font-semibold uppercase tracking-wider text-slate-400">
                Document Preview ({numPages} Pages)
              </span>
              <div className="space-y-4 max-h-56 overflow-y-auto flex flex-col items-center p-2 rounded-lg bg-black/40 border border-slate-800">
                {Array.from({ length: numPages }, (_, i) => (
                  <div key={i} className="shadow-lg bg-white p-1.5 rounded">
                    <p className="text-[10px] text-gray-500 mb-1 text-center font-medium">Page {i + 1}</p>
                    <canvas
                      ref={(el) => {
                        if (el) canvasRefs.current[i] = el;
                      }}
                      className="max-h-48 object-contain rounded"
                    />
                  </div>
                ))}
              </div>
            </div>
          )}

          {error && (
            <div className="bg-red-950/50 border border-red-800/80 text-red-300 text-xs px-4 py-3 rounded-xl">
              {error}
            </div>
          )}

          {/* Submit Button */}
          <button
            type="submit"
            disabled={loading || !file || !password}
            className="w-full bg-gradient-to-r from-cyan-500 to-blue-600 hover:from-cyan-400 hover:to-blue-500 text-white font-semibold py-3.5 px-4 rounded-xl transition-all shadow-lg shadow-cyan-500/20 disabled:opacity-50 text-sm tracking-wide"
          >
            {loading ? "Protecting PDF..." : "Protect and Download PDF"}
          </button>
        </form>

        {/* Secure Footer Note */}
        <div className="flex items-center justify-center space-x-2 text-xs text-slate-400 pt-2 border-t border-slate-800/60">
          <svg className="w-4 h-4 text-cyan-400" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M9 12l2 2 4-4m5.618-4.016A11.955 11.955 0 0112 2.944a11.955 11.955 0 01-8.618 3.04A12.02 12.02 0 003 9c0 5.591 3.824 10.29 9 11.622 5.176-1.332 9-6.03 9-11.622 0-1.042-.133-2.052-.382-3.016z" />
          </svg>
          <span>Secure client-side processing • Password encrypted securely</span>
        </div>

      </div>
    </div>
  );
>>>>>>> 0635d89 ( commit message here)
}