import {
    FileStack,
    Scissors,
    Minimize2,
    FileText,
    RotateCw,
    Droplets,
    Lock,
    Unlock,
    FileImage,
    FileSpreadsheet,
    FileSignature,
    Edit3,
    Sparkles,
    ScanText,
    FileSearch,
    ShieldCheck,
} from "lucide-react";

export const tools = [
    {
        name: "Merge PDF",
        description: "Combine multiple PDF files into one.",
        icon: FileStack,
        href: "/tools/merge-pdf",
        category: "Organize",
        badge: "Popular",
    },
    {
        name: "Split PDF",
        description: "Extract pages from any PDF.",
        icon: Scissors,
        href: "/tools/split-pdf",
        category: "Organize",
    },
    {
        name: "Compress PDF",
        description: "Reduce PDF file size quickly.",
        icon: Minimize2,
        href: "/tools/compress-pdf",
        category: "Edit",
    },
    {
        name: "PDF to Word",
        description: "Convert PDF into editable Word files.",
        icon: FileText,
        href: "/tools/pdf-to-word",
        category: "Convert",
    },
    {
        name: "Word to PDF",
        description: "Convert Word documents into PDF.",
        icon: RotateCw,
        href: "/tools/word-to-pdf",
        category: "Convert",
    },
    {
        name: "PDF to JPG",
        description: "Convert PDF pages into images.",
        icon: FileImage,
        href: "/tools/pdf-to-jpg",
        category: "Convert",
    },
    {
        name: "Excel to PDF",
        description: "Convert spreadsheets into PDFs.",
        icon: FileSpreadsheet,
        href: "/tools/excel-to-pdf",
        category: "Convert",
    },
    {
        name: "Watermark PDF",
        description: "Add text or image watermarks.",
        icon: Droplets,
        href: "/tools/watermark-pdf",
        category: "Edit",
    },
    {
        name: "Sign PDF",
        description: "Add digital signatures instantly.",
        icon: FileSignature,
        href: "/tools/sign-pdf",
        category: "Edit",
    },
    {
        name: "Edit PDF",
        description: "Edit text and images inside PDFs.",
        icon: Edit3,
        href: "/tools/edit-pdf",
        category: "Edit",
    },
    {
        name: "OCR PDF",
        description: "Extract text from scanned PDFs.",
        icon: ScanText,
        href: "/tools/ocr",
        category: "AI Tools",
        badge: "AI",
    },
    {
        name: "AI Summary",
        description: "Generate document summaries instantly.",
        icon: Sparkles,
        href: "/tools/ai-summary",
        category: "AI Tools",
        badge: "AI",
    },
    {
        name: "Chat with PDF",
        description: "Ask questions about your documents.",
        icon: FileSearch,
        href: "/tools/chat-pdf",
        category: "AI Tools",
        badge: "New",
    },
    {
        name: "Protect PDF",
        description: "Encrypt PDF files with passwords.",
        icon: Lock,
        href: "/tools/protect-pdf",
        category: "Security",
    },
    {
        name: "Unlock PDF",
        description: "Remove password protection.",
        icon: Unlock,
        href: "/tools/unlock-pdf",
        category: "Security",
    },
    {
        name: "Secure PDF",
        description: "Advanced security for sensitive files.",
        icon: ShieldCheck,
        href: "/tools/secure-pdf",
        category: "Security",
    },
];